package io.swagger.petstore.assertions.user;

import io.swagger.petstore.models.user.UserModel;
import org.assertj.core.api.AbstractObjectAssert;
import org.assertj.core.util.Objects;

/**
 * Abstract base class for {@link UserModel} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractUserModelAssert<S extends AbstractUserModelAssert<S, A>, A extends UserModel> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractUserModelAssert}</code> to make assertions on actual UserModel.
   * @param actual the UserModel we want to make assertions on.
   */
  protected AbstractUserModelAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

  /**
   * Verifies that the actual UserModel's email is equal to the given one.
   * @param email the given email to compare the actual UserModel's email to.
   * @return this assertion object.
   * @throws AssertionError - if the actual UserModel's email is not equal to the given one.
   */
  public S hasEmail(String email) {
    // check that actual UserModel we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting email of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualEmail = actual.getEmail();
    if (!Objects.areEqual(actualEmail, email)) {
      failWithMessage(assertjErrorMessage, actual, email, actualEmail);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual UserModel's firstName is equal to the given one.
   * @param firstName the given firstName to compare the actual UserModel's firstName to.
   * @return this assertion object.
   * @throws AssertionError - if the actual UserModel's firstName is not equal to the given one.
   */
  public S hasFirstName(String firstName) {
    // check that actual UserModel we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting firstName of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualFirstName = actual.getFirstName();
    if (!Objects.areEqual(actualFirstName, firstName)) {
      failWithMessage(assertjErrorMessage, actual, firstName, actualFirstName);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual UserModel's id is equal to the given one.
   * @param id the given id to compare the actual UserModel's id to.
   * @return this assertion object.
   * @throws AssertionError - if the actual UserModel's id is not equal to the given one.
   */
  public S hasId(int id) {
    // check that actual UserModel we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting id of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // check
    int actualId = actual.getId();
    if (actualId != id) {
      failWithMessage(assertjErrorMessage, actual, id, actualId);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual UserModel's lastName is equal to the given one.
   * @param lastName the given lastName to compare the actual UserModel's lastName to.
   * @return this assertion object.
   * @throws AssertionError - if the actual UserModel's lastName is not equal to the given one.
   */
  public S hasLastName(String lastName) {
    // check that actual UserModel we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting lastName of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualLastName = actual.getLastName();
    if (!Objects.areEqual(actualLastName, lastName)) {
      failWithMessage(assertjErrorMessage, actual, lastName, actualLastName);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual UserModel's password is equal to the given one.
   * @param password the given password to compare the actual UserModel's password to.
   * @return this assertion object.
   * @throws AssertionError - if the actual UserModel's password is not equal to the given one.
   */
  public S hasPassword(String password) {
    // check that actual UserModel we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting password of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualPassword = actual.getPassword();
    if (!Objects.areEqual(actualPassword, password)) {
      failWithMessage(assertjErrorMessage, actual, password, actualPassword);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual UserModel's phone is equal to the given one.
   * @param phone the given phone to compare the actual UserModel's phone to.
   * @return this assertion object.
   * @throws AssertionError - if the actual UserModel's phone is not equal to the given one.
   */
  public S hasPhone(String phone) {
    // check that actual UserModel we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting phone of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualPhone = actual.getPhone();
    if (!Objects.areEqual(actualPhone, phone)) {
      failWithMessage(assertjErrorMessage, actual, phone, actualPhone);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual UserModel's userStatus is equal to the given one.
   * @param userStatus the given userStatus to compare the actual UserModel's userStatus to.
   * @return this assertion object.
   * @throws AssertionError - if the actual UserModel's userStatus is not equal to the given one.
   */
  public S hasUserStatus(int userStatus) {
    // check that actual UserModel we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting userStatus of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // check
    int actualUserStatus = actual.getUserStatus();
    if (actualUserStatus != userStatus) {
      failWithMessage(assertjErrorMessage, actual, userStatus, actualUserStatus);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual UserModel's username is equal to the given one.
   * @param username the given username to compare the actual UserModel's username to.
   * @return this assertion object.
   * @throws AssertionError - if the actual UserModel's username is not equal to the given one.
   */
  public S hasUsername(String username) {
    // check that actual UserModel we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting username of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualUsername = actual.getUsername();
    if (!Objects.areEqual(actualUsername, username)) {
      failWithMessage(assertjErrorMessage, actual, username, actualUsername);
    }

    // return the current assertion for method chaining
    return myself;
  }

}
