package io.swagger.petstore.assertions.user;

import io.swagger.petstore.models.user.UserModel;

/**
 * {@link UserModel} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractUserModelAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class UserModelAssert extends AbstractUserModelAssert<UserModelAssert, UserModel> {

  /**
   * Creates a new <code>{@link UserModelAssert}</code> to make assertions on actual UserModel.
   * @param actual the UserModel we want to make assertions on.
   */
  public UserModelAssert(UserModel actual) {
    super(actual, UserModelAssert.class);
  }

  /**
   * An entry point for UserModelAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myUserModel)</code> and get specific assertion with code completion.
   * @param actual the UserModel we want to make assertions on.
   * @return a new <code>{@link UserModelAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static UserModelAssert assertThat(UserModel actual) {
    return new UserModelAssert(actual);
  }
}
