package io.swagger.petstore.assertions.bad_response;

import io.swagger.petstore.models.bad_response.BadResponse;

/**
 * {@link BadResponse} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractBadResponseModelAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class BadResponseAssert extends AbstractBadResponseModelAssert<BadResponseAssert, BadResponse> {

  /**
   * Creates a new <code>{@link BadResponseAssert}</code> to make assertions on actual BadResponse.
   * @param actual the BadResponse we want to make assertions on.
   */
  public BadResponseAssert(BadResponse actual) {
    super(actual, BadResponseAssert.class);
  }

  /**
   * An entry point for BadResponseAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myPetNotFoundModel)</code> and get specific assertion with code completion.
   * @param actual the BadResponse we want to make assertions on.
   * @return a new <code>{@link BadResponseAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static BadResponseAssert assertThat(BadResponse actual) {
    return new BadResponseAssert(actual);
  }
}
