package io.swagger.petstore.assertions.pet;

import io.swagger.petstore.models.pet.PetBadResponse;

/**
 * {@link PetBadResponse} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractPetBadResponseModelAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class PetBadResponseAssert extends AbstractPetBadResponseModelAssert<PetBadResponseAssert, PetBadResponse> {

  /**
   * Creates a new <code>{@link PetBadResponseAssert}</code> to make assertions on actual PetBadResponse.
   * @param actual the PetBadResponse we want to make assertions on.
   */
  public PetBadResponseAssert(PetBadResponse actual) {
    super(actual, PetBadResponseAssert.class);
  }

  /**
   * An entry point for PetBadResponseAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myPetNotFoundModel)</code> and get specific assertion with code completion.
   * @param actual the PetBadResponse we want to make assertions on.
   * @return a new <code>{@link PetBadResponseAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static PetBadResponseAssert assertThat(PetBadResponse actual) {
    return new PetBadResponseAssert(actual);
  }
}
