package io.swagger.petstore.assertions.order;

import io.swagger.petstore.models.order.OrderModel;

/**
 * {@link OrderModel} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractOrderModelAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class OrderModelAssert extends AbstractOrderModelAssert<OrderModelAssert, OrderModel> {

  /**
   * Creates a new <code>{@link OrderModelAssert}</code> to make assertions on actual OrderModel.
   * @param actual the OrderModel we want to make assertions on.
   */
  public OrderModelAssert(OrderModel actual) {
    super(actual, OrderModelAssert.class);
  }

  /**
   * An entry point for OrderModelAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myOrderModel)</code> and get specific assertion with code completion.
   * @param actual the OrderModel we want to make assertions on.
   * @return a new <code>{@link OrderModelAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static OrderModelAssert assertThat(OrderModel actual) {
    return new OrderModelAssert(actual);
  }
}
